version: '3.2'
services:
  db:
    restart: always
    container_name: sample_db
    image: mysql:5.7
    ports:
      - '5432:5432'
    environment:
        - MYSQL_PASSWORD=${MYSQL_PASSWORD}
        - MYSQL_USER=${MYSQL_USER}
        - MYSQL_DB=${MYSQL_DB}

  web:
    build: .
    expose:
      - '8080'
    ports:
      - '8080:8080'
